"""add notas and observaciones_pdf to cotizaciones

Revision ID: 09ed1cc9085d
Revises: 0aa2f651838b
Create Date: 2026-03-31 08:56:13.260438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ed1cc9085d'
down_revision: Union[str, Sequence[str], None] = '0aa2f651838b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('cotizaciones', sa.Column('observaciones_pdf', sa.Text(), nullable=True))
    op.drop_column('cotizaciones', 'pdf_url')
    op.alter_column('usuarios', 'nombre_completo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuarios', 'cedula_ciudadania',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'cedula_ciudadania',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('usuarios', 'nombre_completo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('cotizaciones', sa.Column('pdf_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cotizaciones', 'observaciones_pdf')
    op.drop_column('cotizaciones', 'notas')
    # ### end Alembic commands ###
