"""add cedula_ciudadania to usuarios

Revision ID: 0aa2f651838b
Revises: e3e24532f82c
Create Date: 2026-03-31 07:38:47.769984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aa2f651838b'
down_revision: Union[str, Sequence[str], None] = 'e3e24532f82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Primero eliminar el FK viejo
    op.drop_constraint('cotizaciones_usuario_id_fkey', 'cotizaciones', type_='foreignkey')

    # 2. Renombrar columnas existentes en usuarios (en vez de drop/add)
    op.alter_column('usuarios', 'usu_id', new_column_name='id')
    op.alter_column('usuarios', 'usu_nombre', new_column_name='usuario')
    op.alter_column('usuarios', 'usu_email', new_column_name='email')
    op.alter_column('usuarios', 'usu_password', new_column_name='clave')
    op.alter_column('usuarios', 'usu_role', new_column_name='rol')
    op.alter_column('usuarios', 'usu_activo', new_column_name='activo')
    op.alter_column('usuarios', 'usu_created_at', new_column_name='created_at')
    op.alter_column('usuarios', 'usu_updated_at', new_column_name='updated_at')

    # 3. Agregar columnas nuevas que realmente no existían
    op.add_column('usuarios', sa.Column('nombre_completo', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('cedula_ciudadania', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['cedula_ciudadania'])

    # 4. Ahora sí crear el FK nuevo apuntando a id que ya existe
    op.create_foreign_key(None, 'cotizaciones', 'usuarios', ['usuario_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('usu_nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('usu_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('usu_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('usu_email', sa.VARCHAR(length=180), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('usu_activo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('usu_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('usu_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('usu_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'created_at')
    op.drop_column('usuarios', 'activo')
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'clave')
    op.drop_column('usuarios', 'cedula_ciudadania')
    op.drop_column('usuarios', 'email')
    op.drop_column('usuarios', 'nombre_completo')
    op.drop_column('usuarios', 'usuario')
    op.drop_column('usuarios', 'id')
    op.drop_constraint(None, 'cotizaciones', type_='foreignkey')
    op.create_foreign_key(op.f('cotizaciones_usuario_id_fkey'), 'cotizaciones', 'usuarios', ['usuario_id'], ['usu_id'])
    # ### end Alembic commands ###
