"""refactor firmas remove archivo descripcion add url

Revision ID: 1f13ad11ea8e
Revises: 12dab7ecdcbe
Create Date: 2026-04-19 18:47:53.396031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f13ad11ea8e'
down_revision: Union[str, Sequence[str], None] = '12dab7ecdcbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
