"""remove activo and orden from productos_multimedia

Revision ID: 30b13c748ce7
Revises: 09ed1cc9085d
Create Date: 2026-04-03 17:23:09.214055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b13c748ce7'
down_revision: Union[str, Sequence[str], None] = '09ed1cc9085d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos_multimedia', 'orden')
    op.drop_column('productos_multimedia', 'activo')
    op.alter_column('usuarios', 'usuario',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    op.alter_column('usuarios', 'usuario',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.add_column('productos_multimedia', sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('productos_multimedia', sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
