"""add_firma_id_to_usuarios_remove_usuario_id_from_firmas

Revision ID: 352a10bd2d99
Revises: 247269bf6e74
Create Date: 2026-05-11 12:38:47.278288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352a10bd2d99'
down_revision: Union[str, Sequence[str], None] = '247269bf6e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('firmas_usuario_id_fkey'), 'firmas', type_='foreignkey')
    op.drop_column('firmas', 'usuario_id')
    op.add_column('usuarios', sa.Column('firma_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'firma_id')
    op.add_column('firmas', sa.Column('usuario_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('firmas_usuario_id_fkey'), 'firmas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
