"""add origen to productos

Revision ID: 3fa0651e20b6
Revises: e98615b3aee6
Create Date: 2026-04-15 18:28:19.239630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa0651e20b6'
down_revision: Union[str, Sequence[str], None] = 'e98615b3aee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('productos', sa.Column('origen', sa.String(length=20), nullable=True))
    op.execute("UPDATE productos SET origen = 'externo' WHERE origen IS NULL")
    op.alter_column('productos', 'origen', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'origen')
    # ### end Alembic commands ###
