"""remove activo from productos

Revision ID: 4fae3a1ec4b5
Revises: e60ebae7dda5
Create Date: 2026-03-27 07:47:34.287450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fae3a1ec4b5'
down_revision: Union[str, Sequence[str], None] = 'e60ebae7dda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'activo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
