"""add por_iva to cotizaciones_items

Revision ID: 5a9351906486
Revises: 7b945fd03e6c
Create Date: 2026-05-13 17:13:30.714002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9351906486'
down_revision: Union[str, Sequence[str], None] = '7b945fd03e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones_items', sa.Column('por_iva', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones_items', 'por_iva')
    # ### end Alembic commands ###
