"""init

Revision ID: 6430ef3b19f5
Revises: 
Create Date: 2026-03-23 11:27:55.104484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6430ef3b19f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('usu_id', sa.Integer(), nullable=False),
    sa.Column('usu_nombre', sa.String(length=120), nullable=False),
    sa.Column('usu_email', sa.String(length=180), nullable=False),
    sa.Column('usu_password', sa.String(length=255), nullable=False),
    sa.Column('usu_role', sa.String(length=50), nullable=False),
    sa.Column('usu_activo', sa.Boolean(), nullable=False),
    sa.Column('usu_created_at', sa.DateTime(), nullable=False),
    sa.Column('usu_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('usu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
