"""remove iva from cotizaciones and items

Revision ID: 6580fc3b7e45
Revises: 352a10bd2d99
Create Date: 2026-05-12 15:52:33.033109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6580fc3b7e45'
down_revision: Union[str, Sequence[str], None] = '352a10bd2d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones', 'iva')
    op.drop_column('cotizaciones_items', 'iva')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones_items', sa.Column('iva', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('cotizaciones', sa.Column('iva', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
