"""add por_iva to productos

Revision ID: 7b945fd03e6c
Revises: 6580fc3b7e45
Create Date: 2026-05-13 16:20:33.408845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b945fd03e6c'
down_revision: Union[str, Sequence[str], None] = '6580fc3b7e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('por_iva', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'por_iva')
    # ### end Alembic commands ###
