"""remove activa from firmas

Revision ID: b3caf9e99c79
Revises: 41c53ab7e680
Create Date: 2026-04-13 15:17:22.985210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3caf9e99c79'
down_revision: Union[str, Sequence[str], None] = '41c53ab7e680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firmas', 'activa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firmas', sa.Column('activa', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
