"""add email_thread_id to cotizaciones

Revision ID: b649a638bd30
Revises: 5d13b5877c2c
Create Date: 2026-05-01 14:39:03.854117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b649a638bd30'
down_revision: Union[str, Sequence[str], None] = '5d13b5877c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('email_thread_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones', 'email_thread_id')
    # ### end Alembic commands ###
