"""add seleccionada to productos_multimedia

Revision ID: c13df048c509
Revises: d3f2df7a459c
Create Date: 2026-04-10 15:47:37.783260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13df048c509'
down_revision: Union[str, Sequence[str], None] = 'd3f2df7a459c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos_multimedia', sa.Column('seleccionada', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos_multimedia', 'seleccionada')
    # ### end Alembic commands ###
