"""remove_orden_metadata_snapshot_cotizaciones_items

Revision ID: c883a1c5f5bb
Revises: 30b13c748ce7
Create Date: 2026-04-06 19:51:19.992017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c883a1c5f5bb'
down_revision: Union[str, Sequence[str], None] = '30b13c748ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('cotizaciones_items', sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    op.add_column('cotizaciones_items', sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    op.add_column('cotizaciones_items', sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    op.add_column('cotizaciones_items', sa.Column('imagen_url', sa.Text(), nullable=True))
    op.add_column('cotizaciones_items', sa.Column('ficha_tecnica_url', sa.Text(), nullable=True))
    op.drop_column('cotizaciones_items', 'subtotal_linea')
    op.drop_column('cotizaciones_items', 'metadata_snapshot')
    op.drop_column('cotizaciones_items', 'total_linea')
    op.drop_column('cotizaciones_items', 'ficha_tecnica_url_snapshot')
    op.drop_column('cotizaciones_items', 'imagen_url_snapshot')
    op.drop_column('cotizaciones_items', 'iva_linea')
    op.drop_column('cotizaciones_items', 'orden')
    op.drop_column('productos', 'sincronizado_at')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('sincronizado_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_items', sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cotizaciones_items', sa.Column('iva_linea', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('cotizaciones_items', sa.Column('imagen_url_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_items', sa.Column('ficha_tecnica_url_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_items', sa.Column('total_linea', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('cotizaciones_items', sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_items', sa.Column('subtotal_linea', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.drop_column('cotizaciones_items', 'ficha_tecnica_url')
    op.drop_column('cotizaciones_items', 'imagen_url')
    op.drop_column('cotizaciones_items', 'total')
    op.drop_column('cotizaciones_items', 'iva')
    op.drop_column('cotizaciones_items', 'subtotal')
    # ### end Alembic commands ###
