"""add_imagenes_urls_fichas_urls_jsonb_to_cotizaciones_items

Revision ID: d3f2df7a459c
Revises: c883a1c5f5bb
Create Date: 2026-04-07 14:54:39.916873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3f2df7a459c'
down_revision: Union[str, Sequence[str], None] = 'c883a1c5f5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones_items', sa.Column('imagenes_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cotizaciones_items', sa.Column('fichas_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('cotizaciones_items', 'ficha_tecnica_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones_items', sa.Column('ficha_tecnica_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cotizaciones_items', 'fichas_urls')
    op.drop_column('cotizaciones_items', 'imagenes_urls')
    # ### end Alembic commands ###
