"""clean cotizaciones models

Revision ID: e3e24532f82c
Revises: 4fae3a1ec4b5
Create Date: 2026-03-28 11:51:55.458787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3e24532f82c'
down_revision: Union[str, Sequence[str], None] = '4fae3a1ec4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotizaciones_historial')
    op.add_column('cotizaciones', sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('cotizaciones', sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False))
    op.drop_column('cotizaciones', 'condiciones_comerciales')
    op.drop_column('cotizaciones', 'iva_total')
    op.drop_column('cotizaciones', 'canal_envio')
    op.drop_column('cotizaciones', 'fecha_generacion')
    op.drop_column('cotizaciones', 'observaciones_pdf')
    op.drop_column('cotizaciones', 'moneda')
    op.drop_column('cotizaciones', 'porcentaje_iva')
    op.drop_column('cotizaciones', 'base_gravable')
    op.drop_column('cotizaciones', 'descuento_total')
    op.drop_column('cotizaciones', 'pdf_nombre')
    op.drop_column('cotizaciones', 'notas')
    op.add_column('cotizaciones_envios', sa.Column('destinatario', sa.String(length=255), nullable=True))
    op.drop_column('cotizaciones_envios', 'asunto')
    op.drop_column('cotizaciones_envios', 'destino')
    op.drop_column('cotizaciones_envios', 'respuesta')
    op.drop_column('cotizaciones_envios', 'mensaje')
    op.drop_constraint(op.f('cotizaciones_items_producto_id_fkey'), 'cotizaciones_items', type_='foreignkey')
    op.drop_column('cotizaciones_items', 'producto_id')
    op.drop_column('cotizaciones_items', 'saldo_referencia')
    op.drop_column('cotizaciones_items', 'unidad_medida')
    op.drop_column('cotizaciones_items', 'valor_web_referencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones_items', sa.Column('valor_web_referencia', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_items', sa.Column('unidad_medida', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_items', sa.Column('saldo_referencia', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_items', sa.Column('producto_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cotizaciones_items_producto_id_fkey'), 'cotizaciones_items', 'productos', ['producto_id'], ['id'])
    op.add_column('cotizaciones_envios', sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_envios', sa.Column('respuesta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_envios', sa.Column('destino', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('cotizaciones_envios', sa.Column('asunto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('cotizaciones_envios', 'destinatario')
    op.add_column('cotizaciones', sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cotizaciones', sa.Column('pdf_nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('cotizaciones', sa.Column('descuento_total', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('cotizaciones', sa.Column('base_gravable', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('cotizaciones', sa.Column('porcentaje_iva', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    op.add_column('cotizaciones', sa.Column('moneda', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('cotizaciones', sa.Column('observaciones_pdf', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cotizaciones', sa.Column('fecha_generacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('cotizaciones', sa.Column('canal_envio', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('cotizaciones', sa.Column('iva_total', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('cotizaciones', sa.Column('condiciones_comerciales', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('cotizaciones', 'iva')
    op.drop_column('cotizaciones', 'descuento')
    op.create_table('cotizaciones_historial',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cotizacion_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('evento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('detalle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('canal', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], name=op.f('cotizaciones_historial_cotizacion_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usu_id'], name=op.f('cotizaciones_historial_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cotizaciones_historial_pkey'))
    )
    # ### end Alembic commands ###
