"""init clean v2

Revision ID: e60ebae7dda5
Revises: 
Create Date: 2026-03-26 19:36:09.216648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e60ebae7dda5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo_cliente', sa.String(length=30), nullable=False),
    sa.Column('nombre_razon_social', sa.String(length=180), nullable=False),
    sa.Column('nit_cedula', sa.String(length=50), nullable=True),
    sa.Column('nombre_contacto', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cod_ref', sa.String(length=80), nullable=False),
    sa.Column('nom_ref', sa.String(length=255), nullable=False),
    sa.Column('cod_tip', sa.String(length=80), nullable=True),
    sa.Column('nom_tip', sa.String(length=150), nullable=True),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_web', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('sincronizado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_ref')
    )
    op.create_table('usuarios',
    sa.Column('usu_id', sa.Integer(), nullable=False),
    sa.Column('usu_nombre', sa.String(length=120), nullable=False),
    sa.Column('usu_email', sa.String(length=180), nullable=False),
    sa.Column('usu_password', sa.String(length=255), nullable=False),
    sa.Column('usu_role', sa.String(length=50), nullable=False),
    sa.Column('usu_activo', sa.Boolean(), nullable=False),
    sa.Column('usu_created_at', sa.DateTime(), nullable=False),
    sa.Column('usu_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('usu_id')
    )
    op.create_table('cotizaciones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consecutivo', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.BigInteger(), nullable=True),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('canal_envio', sa.String(length=30), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('observaciones_pdf', sa.Text(), nullable=True),
    sa.Column('condiciones_comerciales', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('base_gravable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('porcentaje_iva', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('pdf_nombre', sa.String(length=255), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usu_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consecutivo')
    )
    op.create_table('productos_multimedia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones_envios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cotizacion_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_envio', sa.String(length=30), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=True),
    sa.Column('asunto', sa.String(length=255), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('enviado_at', sa.DateTime(), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones_historial',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cotizacion_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('evento', sa.String(length=50), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('canal', sa.String(length=30), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usu_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cotizacion_id', sa.BigInteger(), nullable=False),
    sa.Column('cod_ref', sa.String(length=80), nullable=False),
    sa.Column('nom_ref', sa.String(length=255), nullable=False),
    sa.Column('cod_tip', sa.String(length=80), nullable=True),
    sa.Column('nom_tip', sa.String(length=150), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=30), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo_referencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_web_referencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('imagen_url_snapshot', sa.Text(), nullable=True),
    sa.Column('ficha_tecnica_url_snapshot', sa.Text(), nullable=True),
    sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotizaciones_items')
    op.drop_table('cotizaciones_historial')
    op.drop_table('cotizaciones_envios')
    op.drop_table('productos_multimedia')
    op.drop_table('cotizaciones')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
