"""add usuario_id to firmas

Revision ID: e98615b3aee6
Revises: b3caf9e99c79
Create Date: 2026-04-15 16:19:06.432035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98615b3aee6'
down_revision: Union[str, Sequence[str], None] = 'b3caf9e99c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firmas', sa.Column('usuario_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'firmas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'firmas', type_='foreignkey')
    op.drop_column('firmas', 'usuario_id')
    # ### end Alembic commands ###
