"""add session_token to usuarios

Revision ID: e9e3dd5b3899
Revises: 3fa0651e20b6
Create Date: 2026-04-16 11:21:51.640313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e3dd5b3899'
down_revision: Union[str, Sequence[str], None] = '3fa0651e20b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('session_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'session_token')
    # ### end Alembic commands ###
