# Local desarrollo
server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# Producción frontend
server {
    listen 80;
    server_name app.electromanfer.cimaverso.site;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /media/imagenes/ {
        alias /usr/share/nginx/media/imagenes/;
    }

    location /media/fichas/ {
        alias /usr/share/nginx/media/fichas/;
    }
}

# Producción backend
server {
    listen 80;
    server_name api.electromanfer.cimaverso.site;

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}