server {
    listen 80;
    server_name app.electromanfer.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app.electromanfer.com;
    ssl_certificate /etc/letsencrypt/live/app.electromanfer.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.electromanfer.com/privkey.pem;
    client_max_body_size 50M;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name api.electromanfer.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.electromanfer.com;
    ssl_certificate /etc/letsencrypt/live/app.electromanfer.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.electromanfer.com/privkey.pem;
    client_max_body_size 50M;
    resolver 127.0.0.11 valid=30s;
    set $backend http://backend:8000;

    location /media/imagenes/ {
        alias /usr/share/nginx/media/imagenes/;
        add_header Access-Control-Allow-Origin *;
    }
    location /media/fichas/ {
        alias /usr/share/nginx/media/fichas/;
        add_header Access-Control-Allow-Origin *;
    }
    location /media/firmas/ {
        alias /usr/share/nginx/media/firmas/;
        add_header Access-Control-Allow-Origin *;
    }
    location / {
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect http:// https://;
    }
}